name: Go

on:
  push:
  workflow_dispatch:
    inputs:
      tbBranch:
        description: 'TDengine branch'
        required: true
        type: string


jobs:
  test_arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: checkout TDengine by push
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: main
      
      - name: checkout TDengine manually
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: ${{ inputs.tbBranch }}

      - name: Get CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.31.6

      - name: Cmake TDengine
        run: |
          cd TDengine
          mkdir debug && cd debug
          cmake .. -DBUILD_JDBC=false -DVERNUMBER=3.9.9.9 -DWEBSOCKET=true -DBUILD_DEPENDENCY_TESTS=false

      - name: Make TDengine
        run: |
          cd TDengine/debug/
          make -j8
  test_x86:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout TDengine by push
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          # repository: 'taosdata/TDengine'
          repository: 'freemine/TDengine'
          path: 'TDengine'
          ref: use.lib.for.ext_ssl
      
      - name: checkout TDengine manually
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: ${{ inputs.tbBranch }}

      - name: Get CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.31.6

      - name: Cmake TDengine
        run: |
          cd TDengine
          mkdir debug && cd debug
          cmake .. -DBUILD_JDBC=false -DVERNUMBER=3.9.9.9 -DWEBSOCKET=true -DBUILD_DEPENDENCY_TESTS=false

      - name: Make TDengine
        run: |
          cd TDengine/debug/
          make -j8
